### ISSUE TITLE
Old version in npm

### ISSUE THREAD

**Issue by SnijderC** [timjansen/grunt-hanson-plugin#3]
Would you please release a your latest source (specifically after @lachvoj sent you a merge request) to npm? In modern versions of npm your plugin in broken. See this stack trace:

```
Running "hanson:generic" (hanson) task
Warning: Path must be a string. Received [ 'settings.hson' ] Use --force to continue.
TypeError: Path must be a string. Received [ 'settings.hson' ]
  at assertPath (path.js:28:11)
  at Object.join (path.js:1232:7)
  at Object.file.exists ([redacted-path-to-project]/node_modules/grunt/lib/grunt/file.js:387:28)
  at [redacted-path-to-project]/node_modules/grunt-hanson-plugin/tasks/hanson_plugin.js:29:32
  at Array.forEach (native)
  at Object.<anonymous> ([redacted-path-to-project]/node_modules/grunt-hanson-plugin/tasks/hanson_plugin.js:26:16)
  at Object.<anonymous> ([redacted-path-to-project]/node_modules/grunt/lib/grunt/task.js:255:15)
  at Object.thisTask.fn ([redacted-path-to-project]/node_modules/grunt/lib/grunt/task.js:73:16)
  at Object.<anonymous> ([redacted-path-to-project]/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn ([redacted-path-to-project]/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> ([redacted-path-to-project]/node_modules/grunt/lib/util/task.js:293:12)
  at [redacted-path-to-project]/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:607:11)
  at startup (bootstrap_node.js:158:16)
  at bootstrap_node.js:575:3
```

This is cause by the fact that `f.src` is an array which was fine in older versions of node but now it needs to be a string. Luckily @lachvoj's merge request fixes this bug too. So if you push a new version to npm it should work fine again!

**Comment by timjansen** [comment]
What merge request do you refer to? Can't find any.
